#!/usr/local/bin/python
# -*- coding: utf-8 -*-
"""
Created on Thu Dec  1 21:58:58 2016

@author: pablofernandez
"""
import pymysql.cursors

def connection():
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    connection = pymysql.connect(host='pablofernandez.com',
                             user='pablofer_market',
                             password='G5209sW838sjui6500w',
                             db='pablofer_stockmarket',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    
    return connection
