#!/usr/local/bin/python
# -*- coding: utf-8 -*-
import pymysql.cursors

def connection():
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    connection = pymysql.connect(host='',
                             user='pablofer_market',
                             password='',
                             db='pablofer_stockmarket',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    #**************************** CONFIDENTIAL INFORMATION **************************
    return connection
